image: docker:latest
services:
- docker:dind

variables:
    AWS_ECR_URL: 265635588049.dkr.ecr.us-west-1.amazonaws.com/maze

docker:
    script:
        - apk add --no-cache python py-pip >/dev/null 
        - pip install awscli >/dev/null 
        - $(aws ecr get-login --no-include-email --region us-west-1)
        - docker pull $AWS_ECR_URL:$CI_COMMIT_REF_NAME || true
        - echo $CI_COMMIT_SHA >version
        - docker build -t maze .
        - docker tag maze:latest $AWS_ECR_URL:$CI_COMMIT_REF_NAME
        - docker push $AWS_ECR_URL:$CI_COMMIT_REF_NAME
